import { Project, Task, AttendanceRecord, WeeklyEvaluation, Badge, Certificate, RevenueShare } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-crm",
    title: "Enterprise SaaS CRM & Lead Intelligence Portal",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
    description: "Build an enterprise-grade B2B Customer Relationship Management (CRM) portal featuring visual Kanban sales pipelines, lead scoring algorithms, automated email sequences, and real-time revenue analytics.",
    productIdea: "Full-scale B2B Sales & Pipeline CRM SaaS valued at $180,000.",
    difficulty: "Intermediate",
    seniorityTag: "Mid-Level Engineer",
    requiredSkills: ["React", "Next.js", "Node.js", "PostgreSQL", "Prisma", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "UI UX"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-10",
    endDate: "2026-11-10",
    weeklyHours: 14,
    status: "open",
    applicationDeadline: "2026-08-08",
    techStack: ["Next.js 16", "PostgreSQL", "Prisma ORM", "Recharts", "Resend Email API"],
    mentor: {
      name: "Siddharth Malhotra",
      role: "VP of Product",
      company: "HubSpot / SaaS Founder",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Ananya Roy",
      role: "Full-Stack Tech Lead",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹18,000,000",
    stipend: "₹15,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    gitRepositoryUrl: "https://github.com/careeros-org/enterprise-saas-crm",
    attendanceMeetingUrl: "https://meet.google.com/abc-defg-hij",
    teams: [
      {
        id: "team-1",
        projectId: "proj-crm",
        teamName: "Team 1 - Frontend & AI Pipeline",
        teamLeaderName: "Ananya Roy",
        teamLeaderEmail: "ananya.roy@careeros.in",
        maxSeats: 4,
        filledSeats: 3,
        members: [
          {
            id: "mem-1",
            name: "Ananya Roy",
            email: "ananya.roy@careeros.in",
            domain: "Full Stack",
            role: "Team Leader (TL)",
            avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
            college: "IIT Delhi",
            techStack: ["Next.js 16", "TypeScript", "Tailwind CSS", "Prisma", "PostgreSQL"],
            joinDate: "2026-08-01",
            endDate: "2026-11-01",
            attendanceRate: 98,
            streakDays: 24,
            points: 120,
            score: 96,
          },
          {
            id: "mem-2",
            name: "Bhavesh Rao",
            email: "bhavesh@careeros.in",
            domain: "Frontend",
            role: "UI & Component Intern",
            avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
            college: "BITS Pilani",
            techStack: ["React 19", "Next.js", "Tailwind CSS", "Redux", "Figma"],
            joinDate: "2026-08-05",
            endDate: "2026-11-05",
            attendanceRate: 96,
            streakDays: 14,
            points: 85,
            score: 94,
          },
          {
            id: "mem-3",
            name: "Riya Mehta",
            email: "riya.m@gmail.com",
            domain: "AI/ML",
            role: "Lead Scoring Intern",
            avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
            college: "IIIT Hyderabad",
            techStack: ["Python", "FastAPI", "OpenAI API", "Scikit-Learn", "Pandas"],
            joinDate: "2026-08-10",
            endDate: "2026-11-10",
            attendanceRate: 92,
            streakDays: 10,
            points: 70,
            score: 88,
          },
        ],
      },
      {
        id: "team-2",
        projectId: "proj-crm",
        teamName: "Team 2 - Core Backend & Database",
        teamLeaderName: "Karan Mehta",
        teamLeaderEmail: "karan.m@careeros.in",
        maxSeats: 4,
        filledSeats: 2,
        members: [
          {
            id: "mem-4",
            name: "Karan Mehta",
            email: "karan.m@careeros.in",
            domain: "Backend",
            role: "Team Leader (TL)",
            avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
            college: "IIT Bombay",
            techStack: ["Node.js", "Express", "PostgreSQL", "Redis", "Docker"],
            joinDate: "2026-08-01",
            endDate: "2026-11-01",
            attendanceRate: 99,
            streakDays: 30,
            points: 135,
            score: 97,
          },
          {
            id: "mem-5",
            name: "Arjun Nair",
            email: "arjun.n@gmail.com",
            domain: "Database",
            role: "PostgreSQL & Prisma Intern",
            avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
            college: "VIT Vellore",
            techStack: ["PostgreSQL", "Prisma ORM", "SQL", "Docker", "Node.js"],
            joinDate: "2026-08-12",
            endDate: "2026-11-12",
            attendanceRate: 90,
            streakDays: 8,
            points: 65,
            score: 89,
          },
        ],
      },
    ],
    rewards: [
      "Official 3-Month Full-Stack CRM Internship Certificate",
      "Letter of Recommendation (LOR)",
      "CareerOS Portfolio Verification Badge",
      "5% Revenue Share Payout on SaaS Enterprise Sales"
    ],
    matchPercentage: 96,
    category: "Web Development",
  },
  {
    id: "proj-campus-os",
    title: "College Student Management & Placement OS",
    coverImage: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80",
    description: "Architect a comprehensive Higher Education ERP & Campus Placement OS to manage student enrollment, course attendance, GPA calculations, placement eligibility shortlists, and automated PDF Offer Letter generation.",
    productIdea: "Campus ERP & Placement Automation Software for Indian Universities.",
    difficulty: "Intermediate",
    seniorityTag: "Junior Intern",
    requiredSkills: ["Next.js", "TypeScript", "Express.js", "MongoDB", "PDFKit", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "Testing"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-12",
    endDate: "2026-11-12",
    weeklyHours: 15,
    status: "open",
    applicationDeadline: "2026-08-10",
    techStack: ["React 19", "Express.js", "MongoDB Atlas", "TailwindCSS", "Puppeteer PDF"],
    mentor: {
      name: "Prof. Rajesh Kulkarni",
      role: "Director of Placement Tech",
      company: "IIT Bombay / Campus OS Fellow",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Karan Mehta",
      role: "Senior Backend Lead",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹12,000,000",
    stipend: "₹12,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "Campus ERP Engineering Internship Certificate",
      "University Placement Commendation Letter",
      "5% Equal Team Revenue Share",
      "CareerOS Pro 1-Year Subscription"
    ],
    matchPercentage: 93,
    category: "Web Development",
  },
  {
    id: "proj-1",
    title: "AI Voice-Powered Career Assistant",
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    description: "Build an ultra-fast real-time speech-to-speech AI agent that conducts mock interviews and provides instant audio feedback for SDE candidates.",
    productIdea: "Enterprise B2B AI Voice Screener SaaS valued at $250,000.",
    difficulty: "Advanced",
    seniorityTag: "Senior / Lead Track",
    requiredSkills: ["React", "Next.js", "Python", "WebSockets", "LLMs", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "AI/ML", "UI UX"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-01",
    endDate: "2026-11-01",
    weeklyHours: 15,
    status: "open",
    applicationDeadline: "2026-07-31",
    techStack: ["Next.js 16", "FastAPI", "OpenAI Realtime API", "Pinecone", "TailwindCSS"],
    mentor: {
      name: "Dr. Vikram Sharma",
      role: "Ex-Google AI Lead",
      company: "Google / CareerOS Fellow",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Aarav Gupta",
      role: "Full-Stack Tech Lead",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹25,000,000",
    stipend: "₹15,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "Official 3-Month Internship Certificate",
      "Letter of Recommendation (LOR)",
      "CareerOS Pro 1-Year Subscription",
      "Exclusive Swag Kit (Hoodie & Backpack)",
      "5% Revenue Share Payout on SaaS Sale"
    ],
    matchPercentage: 94,
    category: "AI Track",
  },
  {
    id: "proj-collab-ide",
    title: "Real-Time Collaborative Code Editor & Web IDE",
    coverImage: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&auto=format&fit=crop&q=80",
    description: "Build a browser-based multi-user live code editor (like Google Docs for code) using Monaco Editor, WebSockets for Yjs CRDT real-time sync, multi-cursor presence, and an isolated Docker container execution runner.",
    productIdea: "Cloud IDE & Real-Time Interview Workspace SaaS.",
    difficulty: "Advanced",
    seniorityTag: "Architect / PM Level",
    requiredSkills: ["React", "TypeScript", "WebSockets", "Monaco Editor", "Docker", "Node.js"],
    domainsRequired: ["Frontend", "Backend", "DevOps", "Full Stack"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-15",
    endDate: "2026-11-15",
    weeklyHours: 16,
    status: "open",
    applicationDeadline: "2026-08-12",
    techStack: ["Next.js 16", "Yjs CRDT", "Monaco Editor", "WebSockets", "Docker Runner"],
    mentor: {
      name: "Meera Subramanian",
      role: "Principal Infrastructure Lead",
      company: "Postman",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Sneha Patel",
      role: "Systems Tech Lead",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹20,000,000",
    stipend: "₹16,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "Collaborative Systems Internship Certificate",
      "Direct Technical Interview Referral",
      "5% Revenue Share Payout",
      "CareerOS Pro Access"
    ],
    matchPercentage: 92,
    category: "Web Development",
  },
  {
    id: "proj-ecommerce",
    title: "Multi-Vendor E-Commerce Marketplace & Billing Portal",
    coverImage: "https://images.unsplash.com/photo-1556742049-0a675659e366?w=800&auto=format&fit=crop&q=80",
    description: "Develop a full-featured B2C/B2B e-commerce platform supporting vendor onboarding dashboards, product inventory management, Razorpay payment gateway integration, automated GST invoices, and order tracking.",
    productIdea: "Turnkey Multi-Vendor E-Commerce & Retail SaaS Engine.",
    difficulty: "Intermediate",
    seniorityTag: "Mid-Level Engineer",
    requiredSkills: ["Next.js", "Node.js", "Razorpay API", "PostgreSQL", "Redux Toolkit", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "UI UX"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 2,
    startDate: "2026-08-18",
    endDate: "2026-10-18",
    weeklyHours: 12,
    status: "open",
    applicationDeadline: "2026-08-15",
    techStack: ["Next.js 16", "Express.js", "PostgreSQL", "Razorpay Webhooks", "TailwindCSS"],
    mentor: {
      name: "Amitabh Sen",
      role: "Engineering Director",
      company: "Meesho / Flipkart Alum",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹16,000,000",
    stipend: "₹14,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "E-Commerce Systems Internship Certificate",
      "Letter of Recommendation",
      "5% Equal Team Revenue Sharing",
      "CareerOS Verification Badge"
    ],
    matchPercentage: 95,
    category: "Web Development",
  },
  {
    id: "proj-3",
    title: "Autonomous Code Refactoring Agent",
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80",
    description: "Build an automated GitHub Action agent that parses Pull Requests, analyzes ASTs, fixes TypeScript errors, and optimizes SQL queries.",
    productIdea: "Developer Productivity SaaS Plugin for GitHub & GitLab.",
    difficulty: "Intermediate",
    seniorityTag: "Mid-Level Engineer",
    requiredSkills: ["TypeScript", "Node.js", "AST Parsing", "GitHub API", "React"],
    domainsRequired: ["Frontend", "Backend", "AI/ML", "Product"],
    teamSize: 4,
    filledSeats: 2,
    remainingSeats: 2,
    durationMonths: 2,
    startDate: "2026-08-10",
    endDate: "2026-10-10",
    weeklyHours: 12,
    status: "open",
    applicationDeadline: "2026-08-08",
    techStack: ["TypeScript", "Babel AST", "Octokit", "Next.js"],
    mentor: {
      name: "Priya Nair",
      role: "Staff Engineer",
      company: "Atlassian",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹15,000,000",
    stipend: "₹12,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "Open Source Core Internship Certificate",
      "Letter of Recommendation",
      "Goodie Bag & Custom Keyboard",
      "5% Equal Team Revenue Sharing"
    ],
    matchPercentage: 91,
    category: "Open Source",
  },
  {
    id: "proj-2",
    title: "Distributed High-Frequency Trading Engine",
    coverImage: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80",
    description: "Design a sub-millisecond order matching engine using C++20 and Rust for algorithmic crypto trading and orderbook visualization.",
    productIdea: "Institutional High-Frequency Liquidity Protocol.",
    difficulty: "Expert",
    seniorityTag: "Architect / PM Level",
    requiredSkills: ["C++", "Rust", "System Design", "WebSockets", "Data Structures"],
    domainsRequired: ["Backend", "DevOps", "Testing"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 4,
    startDate: "2026-08-05",
    endDate: "2026-12-05",
    weeklyHours: 20,
    status: "open",
    applicationDeadline: "2026-08-03",
    techStack: ["C++20", "Rust", "gRPC", "Docker", "TimescaleDB"],
    mentor: {
      name: "Rohan Varma",
      role: "Quant Systems Architect",
      company: "Tower Research / AlphaQuant",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Sneha Patel",
      role: "Systems TL",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹40,000,000",
    stipend: "₹20,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "Quant Systems Internship Certificate",
      "Direct Interview Referral to Quant Firms",
      "CareerOS Pro 1-Year Access",
      "5% Revenue Share Payout"
    ],
    matchPercentage: 88,
    category: "ML Systems",
  },
  {
    id: "proj-hospital-mgmt",
    title: "Hospital Healthcare EMR & Patient Management System",
    coverImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80",
    description: "Architect a HIPAA-compliant Hospital Management System featuring Electronic Health Records (EHR), OPD doctor appointment scheduling, bed allocation tracking, digital prescription writer, and automated lab bill generation.",
    productIdea: "Enterprise Digital Health & Clinic Operations SaaS.",
    difficulty: "Intermediate",
    seniorityTag: "Mid-Level Engineer",
    requiredSkills: ["React", "Next.js", "Node.js", "PostgreSQL", "Prisma", "AWS S3"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "Testing"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-20",
    endDate: "2026-11-20",
    weeklyHours: 14,
    status: "open",
    applicationDeadline: "2026-08-18",
    techStack: ["Next.js 16", "PostgreSQL", "Prisma ORM", "AWS S3", "TailwindCSS"],
    mentor: {
      name: "Dr. Ananya Saxena",
      role: "HealthTech Architect",
      company: "Apollo Hospitals / HealthOS",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Rohan Verma",
      role: "Backend Team Lead",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹22,000,000",
    stipend: "₹15,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "HealthTech Systems Engineering Certificate",
      "Letter of Recommendation (LOR)",
      "5% Equal Team Revenue Share",
      "CareerOS Pro 1-Year Subscription"
    ],
    matchPercentage: 94,
    category: "Web Development",
  },
  {
    id: "proj-food-delivery",
    title: "On-Demand Food Delivery & Driver Live GPS Engine",
    coverImage: "https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&auto=format&fit=crop&q=80",
    description: "Build an end-to-end food ordering platform featuring restaurant menu management, live WebSocket GPS tracking for delivery drivers, geofencing notifications, and automated order dispatch logic.",
    productIdea: "Hyperlocal Logistics & Food Tech SaaS Engine.",
    difficulty: "Advanced",
    seniorityTag: "Senior / Lead Track",
    requiredSkills: ["Next.js", "Node.js", "Socket.io", "Redis", "Leaflet Maps", "MongoDB"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "DevOps"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-22",
    endDate: "2026-11-22",
    weeklyHours: 15,
    status: "open",
    applicationDeadline: "2026-08-20",
    techStack: ["React 19", "Express.js", "Socket.io", "Redis Pub/Sub", "Mapbox GL"],
    mentor: {
      name: "Vikramaditya Roy",
      role: "Staff Mobile Systems Lead",
      company: "Swiggy / Zomato Alum",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹19,000,000",
    stipend: "₹14,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "Real-Time Logistics Systems Internship Certificate",
      "Direct Technical Interview Referral",
      "5% Revenue Sharing",
      "CareerOS Verification Badge"
    ],
    matchPercentage: 96,
    category: "Web Development",
  },
  {
    id: "proj-fintech-wallet",
    title: "P2P Digital Payment Wallet & Fraud Detection Engine",
    coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80",
    description: "Design a high-throughput peer-to-peer payment ledger with double-entry accounting integrity, UPI payment gateway simulator, real-time transaction history, and an ML-based anomaly fraud detection filter.",
    productIdea: "Institutional FinTech Payment Infrastructure & Risk Engine.",
    difficulty: "Expert",
    seniorityTag: "Architect / PM Level",
    requiredSkills: ["Go (Golang)", "Next.js", "Kafka", "PostgreSQL", "Python", "Docker"],
    domainsRequired: ["Backend", "DevOps", "AI/ML", "Testing"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 4,
    startDate: "2026-08-25",
    endDate: "2026-12-25",
    weeklyHours: 18,
    status: "open",
    applicationDeadline: "2026-08-23",
    techStack: ["Golang", "Apache Kafka", "PostgreSQL", "Python Scikit-Learn", "Next.js"],
    mentor: {
      name: "Rajesh Kannan",
      role: "Principal FinTech Architect",
      company: "Razorpay / PhonePe",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹35,000,000",
    stipend: "₹18,000 / month + 5% Revenue Share",
    managerName: "Vikramaditya Roy (Handles 6 SaaS Projects)",
    managerEmail: "vikramaditya@careeros.in",
    projectManagerName: "Bhavesh Rao (Dedicated PM)",
    projectManagerEmail: "bhavesh.pm@careeros.in",
    rewards: [
      "FinTech Core Systems Engineering Certificate",
      "Direct Interview Referral to Top FinTechs",
      "5% Equal Team Revenue Share",
      "CareerOS Pro 1-Year Subscription"
    ],
    matchPercentage: 91,
    category: "ML Systems",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    projectId: "proj-crm",
    title: "Implement Realtime Audio Streaming via WebSockets",
    description: "Connect browser MediaRecorder API to OpenAI Realtime API via bi-directional WebSocket connection.",
    createdByRole: "Manager",
    createdByName: "Bhavesh Rao",
    assignedToType: "member",
    assignedTeamId: "team-1",
    assignedTeamName: "Team 1 - Frontend & AI Pipeline",
    assignedMemberId: "mem-2",
    assignedMemberName: "Bhavesh Rao",
    assignedMemberAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    assignedMemberRole: "Full Stack Engineer Intern",
    status: "in_progress",
    priority: "high",
    points: 80,
    dueDate: "2026-09-12",
    internRemarks: "WebSocket handshake completed. Currently handling audio buffer chunking.",
  },
  {
    id: "task-2",
    projectId: "proj-crm",
    title: "Build PostgreSQL Prisma Indexing & Redis Caching Layer",
    description: "Optimize database queries for lead scoring pipeline and set up Redis 60s TTL cache.",
    createdByRole: "Manager",
    createdByName: "Bhavesh Rao",
    assignedToType: "team",
    assignedTeamId: "team-2",
    assignedTeamName: "Team 2 - Core Backend & Database",
    status: "todo",
    priority: "high",
    points: 100,
    dueDate: "2026-09-15",
  },
  {
    id: "task-3",
    projectId: "proj-crm",
    title: "Design Linear-style Audio Waveform Stepper UI",
    description: "Create smooth 60fps canvas audio spectrum analyzer component with custom theme tokens.",
    createdByRole: "Team Leader (TL)",
    createdByName: "Ananya Roy",
    assignedToType: "member",
    assignedTeamId: "team-1",
    assignedTeamName: "Team 1 - Frontend & AI Pipeline",
    assignedMemberId: "mem-1",
    assignedMemberName: "Rohan Sharma",
    assignedMemberAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    assignedMemberRole: "Frontend Intern",
    status: "completed",
    priority: "medium",
    points: 50,
    dueDate: "2026-09-08",
    internRemarks: "Component deployed to staging. Passed all UI responsiveness tests.",
  },
  {
    id: "task-4",
    projectId: "proj-crm",
    title: "Integrate Razorpay Webhook for Lead Intelligence Subscription",
    description: "Handle incoming checkout.session.completed webhooks and update user tier in database.",
    createdByRole: "Manager",
    createdByName: "Bhavesh Rao",
    assignedToType: "unassigned",
    status: "todo",
    priority: "high",
    points: 90,
    dueDate: "2026-09-18",
  },
  {
    id: "task-5",
    projectId: "proj-crm",
    title: "Debug CORS & Auth Header Propagation on Mobile Safari",
    description: "Investigate missing Authorization bearer token during cross-origin preflight fetch requests.",
    createdByRole: "Team Leader (TL)",
    createdByName: "Ananya Roy",
    assignedToType: "member",
    assignedTeamId: "team-1",
    assignedTeamName: "Team 1 - Frontend & AI Pipeline",
    assignedMemberId: "mem-2",
    assignedMemberName: "Bhavesh Rao",
    assignedMemberAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    assignedMemberRole: "Full Stack Engineer Intern",
    status: "issue",
    priority: "high",
    points: 60,
    dueDate: "2026-09-10",
    internRemarks: "Blocked: Safari drops Authorization headers on 302 redirects. Need TL guidance.",
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-1",
    projectId: "proj-crm",
    userId: "mem-2",
    userName: "Bhavesh Rao",
    userRole: "Intern",
    teamId: "team-1",
    teamName: "Team 1 - Frontend & AI Pipeline",
    date: "2026-09-06",
    status: "present",
    approvalStatus: "approved",
    reviewedBy: "TL Ananya Roy",
    remark: "Daily Standup completed on time.",
    verifiedByTL: true,
  },
  {
    id: "att-2",
    projectId: "proj-crm",
    userId: "mem-3",
    userName: "Riya Mehta",
    userRole: "Intern",
    teamId: "team-1",
    teamName: "Team 1 - Frontend & AI Pipeline",
    date: "2026-09-07",
    status: "half_day",
    requestReason: "College Mid-Semester Exam scheduled in the morning session.",
    approvalStatus: "pending",
    verifiedByTL: false,
  },
  {
    id: "att-3",
    projectId: "proj-crm",
    userId: "mem-5",
    userName: "Arjun Nair",
    userRole: "Intern",
    teamId: "team-2",
    teamName: "Team 2 - Core Backend & Database",
    date: "2026-09-05",
    status: "leave",
    requestReason: "Medical Emergency / High Fever",
    approvalStatus: "approved",
    reviewedBy: "TL Karan Mehta",
    remark: "Approved. Get well soon! Catch up on Prisma migrations by Monday.",
    verifiedByTL: true,
  },
  {
    id: "att-4",
    projectId: "proj-crm",
    userId: "mem-1",
    userName: "Ananya Roy",
    userRole: "TL",
    teamId: "team-1",
    teamName: "Team 1 - Frontend & AI Pipeline",
    date: "2026-09-06",
    status: "present",
    approvalStatus: "approved",
    reviewedBy: "PM Bhavesh Rao",
    remark: "Verified by Project Manager & Manager.",
    verifiedByTL: true,
  },
  {
    id: "att-5",
    projectId: "proj-crm",
    userId: "mem-4",
    userName: "Karan Mehta",
    userRole: "TL",
    teamId: "team-2",
    teamName: "Team 2 - Core Backend & Database",
    date: "2026-09-06",
    status: "present",
    approvalStatus: "approved",
    reviewedBy: "PM Bhavesh Rao",
    remark: "Verified by Manager Vikramaditya Roy.",
    verifiedByTL: true,
  },
];

export const MOCK_REVENUE_SHARES: RevenueShare[] = [
  {
    projectId: "proj-1",
    projectTitle: "AI Voice-Powered Career Assistant",
    saleAmount: 2500000, // ₹2,500,000
    tlShare: 125000, // 5% = ₹125,000
    teamSharePerMember: 25000, // 5% total split across 5 members = ₹25,000 each
    careerOSShare: 2250000, // 90% = ₹2,250,000
    status: "approved",
    payoutDate: "2026-08-15",
  },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, name: "Aarav Gupta", college: "IIT Delhi", score: 98, badge: "⚡ Full Stack Hero", projects: 4, avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80" },
  { rank: 2, name: "Sneha Patel", college: "BITS Pilani", score: 95, badge: "🏆 Top Performer", projects: 3, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80" },
  { rank: 3, name: "Bhavesh Rao", college: "VIT Vellore", score: 94, badge: "🔥 Consistency King", projects: 3, avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80" },
  { rank: 4, name: "Ananya Roy", college: "IIIT Hyderabad", score: 91, badge: "🚀 Fast Learner", projects: 2, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80" },
];

export const MOCK_ANNOUNCEMENTS = [
  {
    id: "ann-1",
    projectId: "proj-crm",
    authorName: "Bhavesh Rao",
    authorRole: "Project Manager",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    title: "📢 Sprint 2 Code Review & Architecture Sync",
    content: "Team! Please make sure all PRs for Sprint 2 are submitted before Friday 6:00 PM IST. We will be holding a live code review call with the Project Lead.",
    priority: "urgent",
    createdAt: "2026-09-06T10:00:00Z",
  },
  {
    id: "ann-2",
    projectId: "proj-crm",
    authorName: "Siddharth Malhotra",
    authorRole: "Project Leader",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    title: "🎯 Product Roadmap & Pilot Release",
    content: "Great progress on the Kanban lead pipeline! Our pilot enterprise clients will start onboarding next week. The 5% Revenue Share ledger will be updated right after launch.",
    priority: "important",
    createdAt: "2026-09-05T14:30:00Z",
  },
  {
    id: "ann-3",
    projectId: "proj-crm",
    authorName: "Ananya Roy",
    authorRole: "Team Leader (TL)",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    title: "📌 Task Priority Updates & RLS Security Check",
    content: "Please check the Task List below for updated priorities. Make sure all PostgreSQL schemas have strict RLS policies enabled.",
    priority: "important",
    createdAt: "2026-09-04T09:15:00Z",
  },
  {
    id: "ann-4",
    projectId: "proj-crm",
    authorName: "Karan Mehta",
    authorRole: "Technical Captain",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    title: "⚡ WebSockets API Docs Live",
    content: "The WebSockets API docs and staging environment credentials have been published in the team repository description.",
    priority: "normal",
    createdAt: "2026-09-03T16:00:00Z",
  },
];

export const MOCK_APPLICATIONS = [
  {
    id: "app-101",
    projectId: "proj-crm",
    userId: "u-101",
    applicantName: "Riya Sharma",
    email: "riya.sharma@example.com",
    phone: "+91 98765 43210",
    college: "IIT Delhi",
    degree: "B.Tech Computer Science",
    gradYear: "2026",
    resumeUrl: "https://careeros.app/resumes/riya_sharma_resume.pdf",
    portfolioUrl: "https://riyasharma.dev",
    githubUrl: "https://github.com/riyasharma",
    linkedInUrl: "https://linkedin.com/in/riyasharma",
    whyJoin: "Passionate about full-stack Next.js 16 App Router, real-time WebSocket state management, and building B2B enterprise SaaS CRM dashboards.",
    experience: "Built 3 production Next.js apps with Server Components & WebSockets. Strong TypeScript, Tailwind CSS, and Zustand state management experience.",
    availability: "20 Hours / Week (Dedicated Evening & Weekend Commitment)",
    deliverablesPlan: "I will implement the AST code refactoring UI component library, wire up WebSocket streaming subscriptions, and write automated E2E Playwright tests.",
    pastDeployments: "1. DevConnect SaaS (Deployed on Vercel) — 1,200 monthly active users.\n2. AI Code Inspector CLI (npm package) — 500+ downloads.",
    domain: "Frontend",
    seniorityLevel: "Senior / Lead Track" as const,
    status: "applied" as const,
    appliedAt: "2026-09-05",
    atsScore: 96,
    atsKeywordMatch: 98,
    atsFormattingScore: 94,
    dsaSolvedCount: 184,
    dsaTopicsMastered: [
      { topic: "Arrays & Strings", count: 42 },
      { topic: "Dynamic Programming", count: 28 },
      { topic: "Trees & BST", count: 35 },
      { topic: "Graphs & BFS/DFS", count: 24 },
      { topic: "SQL Queries", count: 20 },
      { topic: "Stacks & Queues", count: 35 },
    ],
    aiMockInterviewScore: 95,
    streakDays: 24,
  },
  {
    id: "app-102",
    projectId: "proj-crm",
    userId: "u-102",
    applicantName: "Dev Patel",
    email: "dev.patel@example.com",
    phone: "+91 98123 65432",
    college: "IIIT Hyderabad",
    degree: "B.Tech Computer Engineering",
    gradYear: "2026",
    resumeUrl: "https://careeros.app/resumes/dev_patel_resume.pdf",
    githubUrl: "https://github.com/devpatel",
    linkedInUrl: "https://linkedin.com/in/devpatel",
    whyJoin: "Eager to engineer high-throughput PostgreSQL database schema migrations, Redis query caching, and Prisma ORM connection pooling.",
    experience: "Node.js microservices, PostgreSQL indexing, Docker, Express, Redis Pub/Sub, and REST API security.",
    availability: "22 Hours / Week (Full Stack Backend Focus)",
    deliverablesPlan: "Will build the Redis Pub/Sub caching layer, optimize PostgreSQL indices for sub-50ms queries, and configure Docker deployment containers.",
    pastDeployments: "1. TaskFlow Microservices (Deployed on AWS EC2).\n2. Open-source Rust CLI query profiler.",
    domain: "Backend",
    seniorityLevel: "Mid-Level Engineer" as const,
    status: "interview_scheduled" as const,
    appliedAt: "2026-09-04",
    interviewDate: "2026-09-08",
    interviewTime: "4:00 PM IST",
    interviewLink: "https://meet.google.com/xyz-1234-abc",
    atsScore: 92,
    atsKeywordMatch: 94,
    atsFormattingScore: 90,
    dsaSolvedCount: 215,
    dsaTopicsMastered: [
      { topic: "Graphs & Shortest Path", count: 45 },
      { topic: "Dynamic Programming", count: 50 },
      { topic: "Arrays & Searching", count: 40 },
      { topic: "SQL & DB Queries", count: 30 },
      { topic: "Trees", count: 50 },
    ],
    aiMockInterviewScore: 92,
    streakDays: 31,
  },
  {
    id: "app-103",
    projectId: "proj-crm",
    userId: "u-103",
    applicantName: "Aarushi Verma",
    email: "aarushi.v@example.com",
    phone: "+91 97111 88822",
    college: "NSUT Delhi",
    degree: "B.Tech Information Technology",
    gradYear: "2027",
    resumeUrl: "https://careeros.app/resumes/aarushi_resume.pdf",
    portfolioUrl: "https://aarushidesign.com",
    linkedInUrl: "https://linkedin.com/in/aarushiverma",
    whyJoin: "Want to architect the design system UI components, WCAG AA accessibility compliance, and responsive dark/light theme tokens.",
    experience: "Figma UI/UX Design System, React 19, Tailwind CSS, Framer Motion, Accessibility (a11y).",
    availability: "18 Hours / Week",
    deliverablesPlan: "Deliver interactive Figma wireframes, component design token tokens, and accessible React UI components.",
    pastDeployments: "1. FinTech Mobile Web App (Figma + Next.js).\n2. E-commerce UI Kit (5,000+ Figma Community Duplicates).",
    domain: "UI UX",
    seniorityLevel: "Junior Intern" as const,
    status: "under_review" as const,
    appliedAt: "2026-09-03",
    atsScore: 89,
    atsKeywordMatch: 90,
    atsFormattingScore: 88,
    dsaSolvedCount: 98,
    dsaTopicsMastered: [
      { topic: "Arrays & Strings", count: 30 },
      { topic: "Recursion & Backtracking", count: 20 },
      { topic: "Trees", count: 25 },
      { topic: "SQL Queries", count: 23 },
    ],
    aiMockInterviewScore: 88,
    streakDays: 14,
  },
  {
    id: "app-104",
    projectId: "proj-crm",
    userId: "u-104",
    applicantName: "Arjun Nair",
    email: "arjun.n@gmail.com",
    phone: "+91 99000 11223",
    college: "BITS Pilani",
    degree: "B.E. Computer Science",
    gradYear: "2026",
    resumeUrl: "https://careeros.app/resumes/arjun_nair_resume.pdf",
    githubUrl: "https://github.com/arjunnair",
    whyJoin: "Database specialist seeking hands-on enterprise SaaS exposure and distributed systems engineering.",
    experience: "PostgreSQL DBA, Redis, Prisma, Node.js, Kubernetes, CI/CD GitHub Actions.",
    availability: "20 Hours / Week",
    deliverablesPlan: "Setup production Supabase database RLS policies, connection poolers, and database backup routines.",
    pastDeployments: "1. Distributed Log Ingestion Engine in Go.\n2. PostgreSQL Analytics Extension.",
    domain: "Backend",
    seniorityLevel: "Architect / PM Level" as const,
    status: "selected" as const,
    appliedAt: "2026-09-01",
    assignedTeamId: "team-2",
    assignedTeamName: "Team 2 - Core Backend & Database",
    assignedTLName: "Karan Mehta",
    atsScore: 95,
    atsKeywordMatch: 97,
    atsFormattingScore: 93,
    dsaSolvedCount: 312,
    dsaTopicsMastered: [
      { topic: "Dynamic Programming", count: 65 },
      { topic: "Graphs & Disjoint Sets", count: 55 },
      { topic: "Arrays & Matrices", count: 60 },
      { topic: "Trees & Tries", count: 50 },
      { topic: "SQL & DB Normalization", count: 42 },
      { topic: "System Design & OOP", count: 40 },
    ],
    aiMockInterviewScore: 96,
    streakDays: 45,
  },
];

