import { Project, Task, AttendanceRecord, WeeklyEvaluation, Badge, Certificate, RevenueShare } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-crm",
    title: "Enterprise SaaS CRM & Lead Intelligence Portal",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
    description: "Build an enterprise-grade B2B Customer Relationship Management (CRM) portal featuring visual Kanban sales pipelines, lead scoring algorithms, automated email sequences, and real-time revenue analytics.",
    productIdea: "Full-scale B2B Sales & Pipeline CRM SaaS valued at $180,000.",
    difficulty: "Intermediate",
    requiredSkills: ["React", "Next.js", "Node.js", "PostgreSQL", "Prisma", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "UI UX"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-10",
    endDate: "2026-11-10",
    weeklyHours: 14,
    status: "open",
    applicationDeadline: "2026-08-08",
    techStack: ["Next.js 16", "PostgreSQL", "Prisma ORM", "Recharts", "Resend Email API"],
    mentor: {
      name: "Siddharth Malhotra",
      role: "VP of Product",
      company: "HubSpot / SaaS Founder",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Ananya Roy",
      role: "Full-Stack Tech Lead",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹18,000,000",
    stipend: "₹15,000 / month + 5% Revenue Share",
    rewards: [
      "Official 3-Month Full-Stack CRM Internship Certificate",
      "Letter of Recommendation (LOR)",
      "CareerOS Portfolio Verification Badge",
      "5% Revenue Share Payout on SaaS Enterprise Sales"
    ],
    matchPercentage: 96,
    category: "Web Development",
  },
  {
    id: "proj-campus-os",
    title: "College Student Management & Placement OS",
    coverImage: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80",
    description: "Architect a comprehensive Higher Education ERP & Campus Placement OS to manage student enrollment, course attendance, GPA calculations, placement eligibility shortlists, and automated PDF Offer Letter generation.",
    productIdea: "Campus ERP & Placement Automation Software for Indian Universities.",
    difficulty: "Intermediate",
    requiredSkills: ["Next.js", "TypeScript", "Express.js", "MongoDB", "PDFKit", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "Testing"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-12",
    endDate: "2026-11-12",
    weeklyHours: 15,
    status: "open",
    applicationDeadline: "2026-08-10",
    techStack: ["React 19", "Express.js", "MongoDB Atlas", "TailwindCSS", "Puppeteer PDF"],
    mentor: {
      name: "Prof. Rajesh Kulkarni",
      role: "Director of Placement Tech",
      company: "IIT Bombay / Campus OS Fellow",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Karan Mehta",
      role: "Senior Backend Lead",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹12,000,000",
    stipend: "₹12,000 / month + 5% Revenue Share",
    rewards: [
      "Campus ERP Engineering Internship Certificate",
      "University Placement Commendation Letter",
      "5% Equal Team Revenue Share",
      "CareerOS Pro 1-Year Subscription"
    ],
    matchPercentage: 93,
    category: "Web Development",
  },
  {
    id: "proj-1",
    title: "AI Voice-Powered Career Assistant",
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    description: "Build an ultra-fast real-time speech-to-speech AI agent that conducts mock interviews and provides instant audio feedback for SDE candidates.",
    productIdea: "Enterprise B2B AI Voice Screener SaaS valued at $250,000.",
    difficulty: "Advanced",
    requiredSkills: ["React", "Next.js", "Python", "WebSockets", "LLMs", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "AI/ML", "UI UX"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-01",
    endDate: "2026-11-01",
    weeklyHours: 15,
    status: "open",
    applicationDeadline: "2026-07-31",
    techStack: ["Next.js 16", "FastAPI", "OpenAI Realtime API", "Pinecone", "TailwindCSS"],
    mentor: {
      name: "Dr. Vikram Sharma",
      role: "Ex-Google AI Lead",
      company: "Google / CareerOS Fellow",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Aarav Gupta",
      role: "Full-Stack Tech Lead",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹25,000,000",
    stipend: "₹15,000 / month + 5% Revenue Share",
    rewards: [
      "Official 3-Month Internship Certificate",
      "Letter of Recommendation (LOR)",
      "CareerOS Pro 1-Year Subscription",
      "Exclusive Swag Kit (Hoodie & Backpack)",
      "5% Revenue Share Payout on SaaS Sale"
    ],
    matchPercentage: 94,
    category: "AI Track",
  },
  {
    id: "proj-collab-ide",
    title: "Real-Time Collaborative Code Editor & Web IDE",
    coverImage: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&auto=format&fit=crop&q=80",
    description: "Build a browser-based multi-user live code editor (like Google Docs for code) using Monaco Editor, WebSockets for Yjs CRDT real-time sync, multi-cursor presence, and an isolated Docker container execution runner.",
    productIdea: "Cloud IDE & Real-Time Interview Workspace SaaS.",
    difficulty: "Advanced",
    requiredSkills: ["React", "TypeScript", "WebSockets", "Monaco Editor", "Docker", "Node.js"],
    domainsRequired: ["Frontend", "Backend", "DevOps", "Full Stack"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-15",
    endDate: "2026-11-15",
    weeklyHours: 16,
    status: "open",
    applicationDeadline: "2026-08-12",
    techStack: ["Next.js 16", "Yjs CRDT", "Monaco Editor", "WebSockets", "Docker Runner"],
    mentor: {
      name: "Meera Subramanian",
      role: "Principal Infrastructure Lead",
      company: "Postman",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Sneha Patel",
      role: "Systems Tech Lead",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹20,000,000",
    stipend: "₹16,000 / month + 5% Revenue Share",
    rewards: [
      "Collaborative Systems Internship Certificate",
      "Direct Technical Interview Referral",
      "5% Revenue Share Payout",
      "CareerOS Pro Access"
    ],
    matchPercentage: 92,
    category: "Web Development",
  },
  {
    id: "proj-ecommerce",
    title: "Multi-Vendor E-Commerce Marketplace & Billing Portal",
    coverImage: "https://images.unsplash.com/photo-1556742049-0a675659e366?w=800&auto=format&fit=crop&q=80",
    description: "Develop a full-featured B2C/B2B e-commerce platform supporting vendor onboarding dashboards, product inventory management, Razorpay payment gateway integration, automated GST invoices, and order tracking.",
    productIdea: "Turnkey Multi-Vendor E-Commerce & Retail SaaS Engine.",
    difficulty: "Intermediate",
    requiredSkills: ["Next.js", "Node.js", "Razorpay API", "PostgreSQL", "Redux Toolkit", "Tailwind CSS"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "UI UX"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 2,
    startDate: "2026-08-18",
    endDate: "2026-10-18",
    weeklyHours: 12,
    status: "open",
    applicationDeadline: "2026-08-15",
    techStack: ["Next.js 16", "Express.js", "PostgreSQL", "Razorpay Webhooks", "TailwindCSS"],
    mentor: {
      name: "Amitabh Sen",
      role: "Engineering Director",
      company: "Meesho / Flipkart Alum",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹16,000,000",
    stipend: "₹14,000 / month + 5% Revenue Share",
    rewards: [
      "E-Commerce Systems Internship Certificate",
      "Letter of Recommendation",
      "5% Equal Team Revenue Sharing",
      "CareerOS Verification Badge"
    ],
    matchPercentage: 95,
    category: "Web Development",
  },
  {
    id: "proj-3",
    title: "Autonomous Code Refactoring Agent",
    coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80",
    description: "Build an automated GitHub Action agent that parses Pull Requests, analyzes ASTs, fixes TypeScript errors, and optimizes SQL queries.",
    productIdea: "Developer Productivity SaaS Plugin for GitHub & GitLab.",
    difficulty: "Intermediate",
    requiredSkills: ["TypeScript", "Node.js", "AST Parsing", "GitHub API", "React"],
    domainsRequired: ["Frontend", "Backend", "AI/ML", "Product"],
    teamSize: 4,
    filledSeats: 2,
    remainingSeats: 2,
    durationMonths: 2,
    startDate: "2026-08-10",
    endDate: "2026-10-10",
    weeklyHours: 12,
    status: "open",
    applicationDeadline: "2026-08-08",
    techStack: ["TypeScript", "Babel AST", "Octokit", "Next.js"],
    mentor: {
      name: "Priya Nair",
      role: "Staff Engineer",
      company: "Atlassian",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹15,000,000",
    stipend: "₹12,000 / month + 5% Revenue Share",
    rewards: [
      "Open Source Core Internship Certificate",
      "Letter of Recommendation",
      "Goodie Bag & Custom Keyboard",
      "5% Equal Team Revenue Sharing"
    ],
    matchPercentage: 91,
    category: "Open Source",
  },
  {
    id: "proj-2",
    title: "Distributed High-Frequency Trading Engine",
    coverImage: "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80",
    description: "Design a sub-millisecond order matching engine using C++20 and Rust for algorithmic crypto trading and orderbook visualization.",
    productIdea: "Institutional High-Frequency Liquidity Protocol.",
    difficulty: "Expert",
    requiredSkills: ["C++", "Rust", "System Design", "WebSockets", "Data Structures"],
    domainsRequired: ["Backend", "DevOps", "Testing"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 4,
    startDate: "2026-08-05",
    endDate: "2026-12-05",
    weeklyHours: 20,
    status: "open",
    applicationDeadline: "2026-08-03",
    techStack: ["C++20", "Rust", "gRPC", "Docker", "TimescaleDB"],
    mentor: {
      name: "Rohan Varma",
      role: "Quant Systems Architect",
      company: "Tower Research / AlphaQuant",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Sneha Patel",
      role: "Systems TL",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹40,000,000",
    stipend: "₹20,000 / month + 5% Revenue Share",
    rewards: [
      "Quant Systems Internship Certificate",
      "Direct Interview Referral to Quant Firms",
      "CareerOS Pro 1-Year Access",
      "5% Revenue Share Payout"
    ],
    matchPercentage: 88,
    category: "ML Systems",
  },
  {
    id: "proj-hospital-mgmt",
    title: "Hospital Healthcare EMR & Patient Management System",
    coverImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80",
    description: "Architect a HIPAA-compliant Hospital Management System featuring Electronic Health Records (EHR), OPD doctor appointment scheduling, bed allocation tracking, digital prescription writer, and automated lab bill generation.",
    productIdea: "Enterprise Digital Health & Clinic Operations SaaS.",
    difficulty: "Intermediate",
    requiredSkills: ["React", "Next.js", "Node.js", "PostgreSQL", "Prisma", "AWS S3"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "Testing"],
    teamSize: 6,
    filledSeats: 4,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-20",
    endDate: "2026-11-20",
    weeklyHours: 14,
    status: "open",
    applicationDeadline: "2026-08-18",
    techStack: ["Next.js 16", "PostgreSQL", "Prisma ORM", "AWS S3", "TailwindCSS"],
    mentor: {
      name: "Dr. Ananya Saxena",
      role: "HealthTech Architect",
      company: "Apollo Hospitals / HealthOS",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    },
    teamLeader: {
      name: "Rohan Verma",
      role: "Backend Team Lead",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹22,000,000",
    stipend: "₹15,000 / month + 5% Revenue Share",
    rewards: [
      "HealthTech Systems Engineering Certificate",
      "Letter of Recommendation (LOR)",
      "5% Equal Team Revenue Share",
      "CareerOS Pro 1-Year Subscription"
    ],
    matchPercentage: 94,
    category: "Web Development",
  },
  {
    id: "proj-food-delivery",
    title: "On-Demand Food Delivery & Driver Live GPS Engine",
    coverImage: "https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&auto=format&fit=crop&q=80",
    description: "Build an end-to-end food ordering platform featuring restaurant menu management, live WebSocket GPS tracking for delivery drivers, geofencing notifications, and automated order dispatch logic.",
    productIdea: "Hyperlocal Logistics & Food Tech SaaS Engine.",
    difficulty: "Advanced",
    requiredSkills: ["Next.js", "Node.js", "Socket.io", "Redis", "Leaflet Maps", "MongoDB"],
    domainsRequired: ["Frontend", "Backend", "Full Stack", "DevOps"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 3,
    startDate: "2026-08-22",
    endDate: "2026-11-22",
    weeklyHours: 15,
    status: "open",
    applicationDeadline: "2026-08-20",
    techStack: ["React 19", "Express.js", "Socket.io", "Redis Pub/Sub", "Mapbox GL"],
    mentor: {
      name: "Vikramaditya Roy",
      role: "Staff Mobile Systems Lead",
      company: "Swiggy / Zomato Alum",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹19,000,000",
    stipend: "₹14,000 / month + 5% Revenue Share",
    rewards: [
      "Real-Time Logistics Systems Internship Certificate",
      "Direct Technical Interview Referral",
      "5% Revenue Sharing",
      "CareerOS Verification Badge"
    ],
    matchPercentage: 96,
    category: "Web Development",
  },
  {
    id: "proj-fintech-wallet",
    title: "P2P Digital Payment Wallet & Fraud Detection Engine",
    coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=80",
    description: "Design a high-throughput peer-to-peer payment ledger with double-entry accounting integrity, UPI payment gateway simulator, real-time transaction history, and an ML-based anomaly fraud detection filter.",
    productIdea: "Institutional FinTech Payment Infrastructure & Risk Engine.",
    difficulty: "Expert",
    requiredSkills: ["Go (Golang)", "Next.js", "Kafka", "PostgreSQL", "Python", "Docker"],
    domainsRequired: ["Backend", "DevOps", "AI/ML", "Testing"],
    teamSize: 5,
    filledSeats: 3,
    remainingSeats: 2,
    durationMonths: 4,
    startDate: "2026-08-25",
    endDate: "2026-12-25",
    weeklyHours: 18,
    status: "open",
    applicationDeadline: "2026-08-23",
    techStack: ["Golang", "Apache Kafka", "PostgreSQL", "Python Scikit-Learn", "Next.js"],
    mentor: {
      name: "Rajesh Kannan",
      role: "Principal FinTech Architect",
      company: "Razorpay / PhonePe",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    },
    estimatedProductValue: "₹35,000,000",
    stipend: "₹18,000 / month + 5% Revenue Share",
    rewards: [
      "FinTech Core Systems Engineering Certificate",
      "Direct Interview Referral to Top FinTechs",
      "5% Equal Team Revenue Share",
      "CareerOS Pro 1-Year Subscription"
    ],
    matchPercentage: 91,
    category: "ML Systems",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    projectId: "proj-1",
    title: "Implement Realtime Audio Streaming via WebSockets",
    description: "Connect browser MediaRecorder API to OpenAI Realtime API via bi-directional WebSocket connection.",
    assignee: {
      name: "Bhavesh Rao",
      avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
      role: "Frontend Engineer",
    },
    status: "in_progress",
    priority: "high",
    points: 8,
    dueDate: "2026-08-05",
  },
  {
    id: "task-2",
    projectId: "proj-1",
    title: "Design Linear-style Audio Waveform Stepper UI",
    description: "Create smooth 60fps canvas audio spectrum analyzer component with custom theme tokens.",
    assignee: {
      name: "Sneha Patel",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      role: "UI/UX Designer",
    },
    status: "done",
    priority: "medium",
    points: 5,
    dueDate: "2026-08-02",
  },
  {
    id: "task-3",
    projectId: "proj-1",
    title: "Build Pinecone Vector Search for Interview Question Bank",
    description: "Index 500+ DSA and System Design prompts into 1536-dim embedding vectors.",
    assignee: {
      name: "Aarav Gupta",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      role: "AI Engineer",
    },
    status: "todo",
    priority: "high",
    points: 10,
    dueDate: "2026-08-08",
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  { id: "att-1", projectId: "proj-1", userId: "u-1", date: "2026-07-27", status: "present", verifiedByTL: true },
  { id: "att-2", projectId: "proj-1", userId: "u-1", date: "2026-07-26", status: "present", verifiedByTL: true },
  { id: "att-3", projectId: "proj-1", userId: "u-1", date: "2026-07-25", status: "present", verifiedByTL: true },
  { id: "att-4", projectId: "proj-1", userId: "u-1", date: "2026-07-24", status: "half_day", verifiedByTL: true },
  { id: "att-5", projectId: "proj-1", userId: "u-1", date: "2026-07-23", status: "present", verifiedByTL: true },
];

export const MOCK_REVENUE_SHARES: RevenueShare[] = [
  {
    projectId: "proj-1",
    projectTitle: "AI Voice-Powered Career Assistant",
    saleAmount: 2500000, // ₹2,500,000
    tlShare: 125000, // 5% = ₹125,000
    teamSharePerMember: 25000, // 5% total split across 5 members = ₹25,000 each
    careerOSShare: 2250000, // 90% = ₹2,250,000
    status: "approved",
    payoutDate: "2026-08-15",
  },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, name: "Aarav Gupta", college: "IIT Delhi", score: 98, badge: "⚡ Full Stack Hero", projects: 4, avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80" },
  { rank: 2, name: "Sneha Patel", college: "BITS Pilani", score: 95, badge: "🏆 Top Performer", projects: 3, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80" },
  { rank: 3, name: "Bhavesh Rao", college: "VIT Vellore", score: 94, badge: "🔥 Consistency King", projects: 3, avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80" },
  { rank: 4, name: "Ananya Roy", college: "IIIT Hyderabad", score: 91, badge: "🚀 Fast Learner", projects: 2, avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80" },
];
